import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    // The test/ suites are plain CommonJS Node scripts by design — they
    // `require()` the esbuild output and drive real Electron windows — a
    // different convention from src/'s bundled TypeScript, not an oversight.
    // scripts/ is likewise small standalone Node tooling. Linting is scoped to
    // what src/ actually is: TypeScript, bundled by esbuild.
    ignores: [
      'dist/**',
      'release/**',
      'node_modules/**',
      'models/**',
      'test/**',
      'scripts/**',
      // Regenerated by `astryx theme build`; CONTRIBUTING.md already says not
      // to hand-edit these, and a linter shouldn't ask you to either.
      'src/renderer/theme/neutral.js',
      'src/renderer/theme/neutral.d.ts',
      'src/renderer/theme/neutral.variants.d.ts',
    ],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [...tseslint.configs.recommended],
  },
  {
    files: ['src/renderer/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      // `const { omitted, ...rest } = x` is how this codebase drops a field
      // rather than picking the others back out one by one (see
      // transcript-export.ts). The sibling is deliberately unused; that's the
      // point of the pattern, not a mistake to flag.
      '@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }],
    },
  },
);
